index:
    path: /
    controller: App\Controller\AppController::index

getTimer:
    path: /getTimer
    controller: App\Controller\AppController::getTimer

restartTimer:
    path: /restartTimer
    controller: App\Controller\AppController::restartTimer

getBestTimer:
    path: /getBestTimer
    controller: App\Controller\AppController::getBestTimer